// Só o CONTEÚDO do dicionário fica aqui.

export type Categoria = 'BARES' | 'RESTAURANTES' | 'CULTURA' | 'OUTROS'

export type PalavraComPeso = { palavra: string; peso: number }

export const DICIONARIO_VIBES: Record<Exclude<Categoria, 'OUTROS'>, PalavraComPeso[]> = {
  BARES: [
    { palavra: 'álcool', peso: 3 },
    { palavra: 'álcoolico', peso: 2 },
    { palavra: 'farra', peso: 2 },
    { palavra: 'farrear', peso: 2 },
    { palavra: 'revoada', peso: 3 },
    { palavra: 'baile', peso: 2 },
    { palavra: 'baile funk', peso: 1 },
    { palavra: 'balada', peso: 3 },
    { palavra: 'chop', peso: 2 },
    { palavra: 'chope', peso: 3 },
    { palavra: 'beber', peso: 3 },
    { palavra: 'breja', peso: 3 },
    { palavra: 'tomar uma', peso: 3 },
    { palavra: 'bar', peso: 3 },
    { palavra: 'bares', peso: 3 },
    { palavra: 'noite', peso: 1 },
    { palavra: 'noitada', peso: 3 },
    { palavra: 'noturna', peso: 3 },
    { palavra: 'cerveja', peso: 3 },
    { palavra: 'chopp', peso: 3 },
    { palavra: 'drink', peso: 2 },
    { palavra: 'happy hour', peso: 3 },
    { palavra: 'resenha', peso: 2 },
    { palavra: 'som', peso: 1 },
    { palavra: 'festa', peso: 2 },
    { palavra: 'pagode', peso: 2 },
    { palavra: 'forró', peso: 2 },
    { palavra: 'dançar', peso: 2 },
    { palavra: 'boteco', peso: 3 },
    { palavra: 'petisco', peso: 1 },
    { palavra: 'sinuca', peso: 2 },
    { palavra: 'choperia', peso: 3 },
    { palavra: 'pub', peso: 3 },
    { palavra: 'rock', peso: 2 },
    { palavra: 'rock and roll', peso: 3 },
    { palavra: 'eletrônica', peso: 3 },
    { palavra: 'música eletrônica', peso: 3 },
    { palavra: 'dj', peso: 2 },
    { palavra: 'caipirinha', peso: 3 },
    { palavra: 'feijoada', peso: 2 },
    { palavra: 'petiscos', peso: 2 },
    { palavra: 'porção', peso: 2 },
    { palavra: 'ao vivo', peso: 2 },
    { palavra: 'música ao vivo', peso: 3 },
    { palavra: 'rua', peso: 2 },
    { palavra: 'curtir', peso: 3 },
    { palavra: 'esquenta', peso: 2 },
    { palavra: 'azaração', peso: 2 },
    { palavra: 'paquera', peso: 2 },
    { palavra: 'fervo', peso: 3 },
    { palavra: 'sacada', peso: 1 },
    { palavra: 'quintal', peso: 2 },
    { palavra: 'esquina', peso: 2 },
    { palavra: 'destilado', peso: 2 },
    { palavra: 'gin', peso: 2 },
    { palavra: 'whisky', peso: 2 },
    { palavra: 'combo', peso: 2 },
    { palavra: 'espetinho', peso: 2 },
    { palavra: 'espeto', peso: 1 },
    { palavra: 'rodízio', peso: 3 },
    { palavra: 'karaokê', peso: 2 },
    { palavra: 'bilhar', peso: 2 },
    { palavra: 'futebol', peso: 2 },
    { palavra: 'jogo', peso: 1 },
    { palavra: 'transmissão', peso: 2 },
    { palavra: 'tabacaria', peso: 2 },
    { palavra: 'luderia', peso: 3 },
    { palavra: 'tira gosto', peso: 2 },
    { palavra: 'cachaça', peso: 2 },
    { palavra: 'vodka', peso: 2 },
    { palavra: 'long neck', peso: 2 },
    { palavra: 'petisqueira', peso: 3 },
    { palavra: 'roda de viola', peso: 3 },
    { palavra: 'reggae', peso: 2 },
    { palavra: 'samba', peso: 2 },
    { palavra: 'chorinho', peso: 2 },
    { palavra: 'vinho', peso: 2 },

    //OCASIÃO

    { palavra: 'date', peso: 2 },
    { palavra: 'encontro', peso: 2 },
    { palavra: 'aniversário', peso: 2 },
    { palavra: 'niver', peso: 2 },
    { palavra: 'aniversario', peso: 2 },
    { palavra: 'despedida', peso: 3 },
    { palavra: 'despedida de solteiro', peso: 3 },
    { palavra: 'comemorar', peso: 3 },
    { palavra: 'chorar', peso: 3 },
    { palavra: 'amigos chegando na cidade', peso: 3 },
    { palavra: 'chuva', peso: 3 },
    { palavra: 'galera', peso: 2 },
    { palavra: 'em grupo', peso: 2 },
    { palavra: 'depois do trabalho', peso: 3 },
    { palavra: 'fim de tarde', peso: 1 },
    { palavra: 'chill', peso: 1 },
    { palavra: 'tranquilo', peso: 1 },
    { palavra: 'barato', peso: 1 },
    { palavra: 'fim de tarde', peso: 2 },
    { palavra: 'finzinho de tarde', peso: 2 },
    { palavra: 'final de tarde', peso: 2 },
    { palavra: 'sextou', peso: 3 },
    { palavra: 'fim de semana', peso: 3 },
    { palavra: 'final de semana', peso: 3 },
    { palavra: 'tardezinha', peso: 3 }
    
  ],
  RESTAURANTES: [
    { palavra: 'date', peso: 3 },
    { palavra: 'bandeco', peso: 2 },
    { palavra: 'bandecar', peso: 3 },
    { palavra: 'rango', peso: 3 },
    { palavra: 'comer', peso: 2 },
    { palavra: 'comida', peso: 2 },
    { palavra: 'prato', peso: 2 },
    { palavra: 'jantar', peso: 3 },
    { palavra: 'almoço', peso: 3 },
    { palavra: 'restaurante', peso: 3 },
    { palavra: 'fominha', peso: 2 },
    { palavra: 'lanche', peso: 2 },
    { palavra: 'sobremesa', peso: 2 },
    { palavra: 'pizza', peso: 3 },
    { palavra: 'hambúrguer', peso: 3 },
    { palavra: 'churrasco', peso: 3 },
    { palavra: 'fome', peso: 2 },
    { palavra: 'brunch', peso: 3 },
    { palavra: 'bistrô', peso: 3 },
    { palavra: 'fine dining', peso: 3 },
    { palavra: 'frutos do mar', peso: 3 },
    { palavra: 'arroz de cuxá', peso: 3 },
    { palavra: 'culinária regional', peso: 3 },
    { palavra: 'comida regional', peso: 3 },
    { palavra: 'prato típico', peso: 3 },
    { palavra: 'vegano', peso: 3 },
    { palavra: 'opção vegana', peso: 3 },
    { palavra: 'café', peso: 2 },
    { palavra: 'cafeteria', peso: 3 },
    { palavra: 'cachorro-quente', peso: 2 },
    { palavra: 'praça de alimentação', peso: 2 },
    { palavra: 'orla', peso: 2 },
    { palavra: 'pôr do sol', peso: 2 },
    { palavra: 'vista para o mar', peso: 3 },
    { palavra: 'massa', peso: 2 },
    { palavra: 'pasta', peso: 2 },
    { palavra: 'carne', peso: 2 },
    { palavra: 'peixe', peso: 2 },
    { palavra: 'camarão', peso: 2 },
    { palavra: 'sushi', peso: 3 },
    { palavra: 'japonesa', peso: 3 },
    { palavra: 'culinária', peso: 2 },
    { palavra: 'gourmet', peso: 3 },
    { palavra: 'menu', peso: 1 },
    { palavra: 'cardápio', peso: 1 },
    { palavra: 'almoçar', peso: 3 },
    { palavra: 'jantarzinho', peso: 3 },
    { palavra: 'confeitaria', peso: 1 },
    { palavra: 'doce', peso: 2 },
    { palavra: 'padaria', peso: 2 },
    { palavra: 'café da manhã', peso: 2 },
    { palavra: 'hamburguer', peso: 3 },
    { palavra: 'pastel', peso: 2 },
    { palavra: 'broca', peso: 3 },
    { palavra: 'brocado', peso: 3 },
    { palavra: 'larica', peso: 3 },
    { palavra: 'prato do dia', peso: 3 },
    { palavra: 'executivo', peso: 2 },
    { palavra: 'bufê', peso: 2 },
    { palavra: 'self-service', peso: 3 },
    { palavra: 'marmita', peso: 2 },
    { palavra: 'delivery', peso: 1 },
    { palavra: 'food truck', peso: 3 },
    { palavra: 'tapioca', peso: 2 },
    { palavra: 'crepe', peso: 2 },
    { palavra: 'milk-shake', peso: 2 },
    { palavra: 'suco', peso: 1 },
    { palavra: 'bolo', peso: 2 },

    //OCASIÃO

    { palavra: 'encontro', peso: 3 },
    { palavra: 'aniversário', peso: 3 },
    { palavra: 'niver', peso: 3 },
    { palavra: 'aniversario', peso: 3 },
    { palavra: 'comemorar', peso: 2 },
    { palavra: 'trabalho', peso: 3 },
    { palavra: 'trabalhar', peso: 3 },
    { palavra: 'amigos chegando na cidade', peso: 3 },
    { palavra: 'chuva', peso: 3 },
    { palavra: 'romântico', peso: 3 },
    { palavra: 'família', peso: 3 },
    { palavra: 'primeiro encontro', peso: 2 },
    { palavra: 'em grupo', peso: 2 },
    { palavra: 'galera', peso: 1 },
    { palavra: 'barato', peso: 1 },
    { palavra: 'fim de tarde', peso: 1 },
    { palavra: 'finzinho de tarde', peso: 1 },
    { palavra: 'final de tarde', peso: 1 },
    { palavra: 'sextou', peso: 2 },
    { palavra: 'fim de semana', peso: 2 },
    { palavra: 'final de semana', peso: 2 },
    { palavra: 'tardezinha', peso: 2 },
    { palavra: 'sozinho', peso: 1 },
    { palavra: 'sozinha', peso: 1 }

  ],
  CULTURA: [
    { palavra: 'reservado', peso: 1 },
    { palavra: 'show', peso: 3 },
    { palavra: 'teatro', peso: 3 },
    { palavra: 'expo', peso: 2 },
    { palavra: 'exposição', peso: 3 },
    { palavra: 'exposicao', peso: 3 },
    { palavra: 'museu', peso: 3 },
    { palavra: 'arte', peso: 2 },
    { palavra: 'cinema', peso: 3 },
    { palavra: 'peça', peso: 2 },
    { palavra: 'cultura', peso: 2 },
    { palavra: 'música', peso: 1 },
    { palavra: 'livro', peso: 2 },
    { palavra: 'literatura', peso: 2 },
    { palavra: 'sarau', peso: 3 },
    { palavra: 'feira', peso: 1 },
    { palavra: 'vinil', peso: 1 },
    { palavra: 'centro cultural', peso: 3 },
    { palavra: 'artes visuais', peso: 3 },
    { palavra: 'arte contemporânea', peso: 3 },
    { palavra: 'oficina', peso: 2 },
    { palavra: 'oficina cultural', peso: 3 },
    { palavra: 'roda de conversa', peso: 2 },
    { palavra: 'independente', peso: 2 },
    { palavra: 'cena urbana', peso: 3 },
    { palavra: 'lifestyle', peso: 2 },
    { palavra: 'jogos de tabuleiro', peso: 3 },
    { palavra: 'rpg', peso: 3 },
    { palavra: 'sebo', peso: 3 },
    { palavra: 'disco', peso: 2 },
    { palavra: 'gratuito', peso: 2 },
    { palavra: 'entrada gratuita', peso: 3 },
    { palavra: 'workshop', peso: 3 },
    { palavra: 'palestra', peso: 2 },
    { palavra: 'debate', peso: 2 },
    { palavra: 'poesia', peso: 2 },
    { palavra: 'ensaio', peso: 2 },
    { palavra: 'orquestra', peso: 3 },
    { palavra: 'clássico', peso: 1 },
    { palavra: 'patrimônio', peso: 3 },
    { palavra: 'histórico', peso: 2 },
    { palavra: 'arquitetura', peso: 2 },
    { palavra: 'fotografia', peso: 2 },
    { palavra: 'foto', peso: 1 },
    { palavra: 'ateliê', peso: 3 },
    { palavra: 'criativo', peso: 2 },
    { palavra: 'rap', peso: 3 },
    { palavra: 'trap', peso: 3 },
    { palavra: 'cultural', peso: 3 },
    { palavra: 'dança', peso: 2 },
    { palavra: 'balé', peso: 3 },
    { palavra: 'documentário', peso: 3 },
    { palavra: 'curta-metragem', peso: 2 },
    { palavra: 'artesanato', peso: 3 },
    { palavra: 'biblioteca', peso: 3 },
    { palavra: 'slam', peso: 3 },
    { palavra: 'capoeira', peso: 3 },
    { palavra: 'maracatu', peso: 3 },
    { palavra: 'bumba boi', peso: 3 },
    { palavra: 'festival', peso: 3 },

    //OCASIÃO

    { palavra: 'date', peso: 1 },
    { palavra: 'encontro', peso: 1 },
    { palavra: 'comemorar', peso: 1 },
    { palavra: 'amigos chegando na cidade', peso: 3 },
    { palavra: 'turismo', peso: 3 },
    { palavra: 'chuva', peso: 3 },
    { palavra: 'primeiro encontro', peso: 3 },
    { palavra: 'família', peso: 2 },
    { palavra: 'romântico', peso: 2 },
    { palavra: 'chill', peso: 1 },
    { palavra: 'tranquilo', peso: 1 },
    { palavra: 'barato', peso: 1 },
    { palavra: 'fim de tarde', peso: 1 },
    { palavra: 'finzinho de tarde', peso: 1 },
    { palavra: 'final de tarde', peso: 1 },
    { palavra: 'sozinho', peso: 3 },
    { palavra: 'sozinha', peso: 3 }

  ]
}